spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_social?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 123456
  jpa:
    show-sql: true
Flyway:
  url: jdbc:mysql://localhost:3306/spring_social
  schemas: spring_social
  user: "root"
  password: 123456