#logging:
#  level:
#    root: trace
#    org:
#      springframework:
#        security:
#          oauth2: trace
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_social?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          #          google:
          #            clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
          #            clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
          #            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
          #            scope:
          #              - email
          #              - profile
          #          facebook:
          #            clientId: 121189305185277
          #            clientSecret: 42ffe5aa7379e8326387e0fe16f34132
          #            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
          #            scope:
          #              - email
          #              - public_profile
          #          github:
          #            clientId: d3e47fc2ddd966fa4352
          #            clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
          #            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
          #            scope:
          #              - user:email
          #              - read:user
          zalo:
            client-id: your-client-id
            clientSecret: your-key
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
        #              client-authentication-method: "client_secret_post"
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
          zalo:
            token-uri: https://oauth.zaloapp.com/v4/access_token
            authorization-uri: https://oauth.zaloapp.com/v4/permission
            user-info-uri: https://graph.zalo.me/v2.0/me?fields=id,name,picture
            user-name-attribute: name
Flyway:
  url: jdbc:mysql://localhost:3306/spring_social
  schemas: spring_social
  user: "root"
  password: 123456
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect